version: '3'
services:

  postgres:
    image: "postgres:14.5"
    ports:
      - "5433:5432"
    volumes:
      - ~/onewin-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
  bot:
    build: .
    ports:
      - "5143:5143"
    restart: always

